****---
title: "Animation Illustrating Gibbs Sampler"
output: html_document
---

```{r}
### Function running Gibbs Sampler for M iterations within initatial variance "init"
run_gibbs_sampler = function(M, init){
  x = matrix(ncol=2, nrow = M)
  ## initial condition
  x[1,1] = init
  
  x[1, 2] = rnorm(n = 1, 
                mean = ( n*ybar + k*lambda ) / ( n + k) , 
                sd = sqrt( x[1, 1]/(n+k) ) )

  
  ## simulate
  for(m in 2:M){
    
    x[m, 1] = invgamma::rinvgamma(n = 1,
                                  shape = ( alpha + n/2 + 1/2 ), 
                                  rate = ( .5*sum( ( y - x[m-1, 2] )^2) + .5*k*( (x[m-1, 2]- lambda )^2)+ beta) )
    
    x[m, 2] = rnorm(n = 1, 
                mean = ( n*ybar + k*lambda ) / ( n + k) , 
                sd = sqrt( x[m, 1]/(n+k) ) )
  }
  return(x)    
}

## joint density function of true posterior
## used to plot contours
post = function(mu, phi){
  
  post_mean = (n*ybar + k*lambda)/(n+k)
  post_sd = sqrt( phi/(n+k) )
  
  post_shape = alpha + n/2
  post_rate = .5*(n-1)*s2 + .5*( (n*k) / (n+k))*(ybar - lambda)^2 + beta
  
  eval = dnorm(mu, mean = post_mean, sd = post_sd ) *
    invgamma::dinvgamma(phi, shape = post_shape, rate = post_rate)

  return(eval)
}
```


```{r, fig.show='animate', fig.width=12, interval=1, fig.height=4, cache=T, aniopts="loop", animation.hook='gifski', fig.align='center'}
library(LaplacesDemon)
library(latex2exp)

set.seed(1)

### choose hyperparameters
alpha = 1
beta = 2
lambda = 0
k = 1

### simulate some data
set.seed(1)
y = rnorm(n = 30, mean = 0, sd=5)

## calculate statistics
n = length(y) ## sample size
ybar = mean(y)  ## sample mean
s2 = (1/(n-1))*sum((y-ybar)^2) ## sample standard deviation


M=100 ## number of mcmc iterations

## run three chains with different initial values
xx = run_gibbs_sampler(M, init=40) 
yy = run_gibbs_sampler(M, init=50)
zz = run_gibbs_sampler(M, init=30)

## plot contours of density
mu     <- seq(-5, 5, 0.25) 
phi     <- seq(0, 50, 0.25)
density_posterior     <- outer(mu, phi, post)

```

Make animation showing three different chains converging to posterior.

```{r, fig.show='animate', fig.width=12, interval=1, fig.height=4, cache=T, aniopts="loop", animation.hook='gifski', fig.align='center'}

par(mfrow=c(1,3))
for(m in 1:M){ ## loop through mcmc iterations
  
  ## plot chain 1 from iteration 1 up through iteration m
  contour(mu, phi, density_posterior, nlevels = 30, 
          main = TeX('Chain 1, $\\phi^{(0)} = 40$'),
        xlab=TeX("$\\mu^{(m)}$"), ylab=TeX("$\\phi^{(m)}$"), xlim=c(-5,5), ylim=c(0,60) )
  lines(xx[1:m,2], xx[1:m,1], type='l', col='blue')

  ## plot chain 2 from iteration 1 up through iteration m
  contour(mu, phi, density_posterior, nlevels = 30, 
          main = TeX('Chain 2, $\\phi^{(0)} = 50$'),
          xlab=TeX("$\\mu^{(m)}$"), ylab=TeX("$\\phi^{(m)}$"), xlim=c(-5,5), ylim=c(0,60) )
  lines(yy[1:m,2], yy[1:m,1], col='orange', type='l')

  ## plot chain 3 from iteration 1 up through iteration m
  contour(mu, phi, density_posterior, nlevels = 30, 
          main = TeX('Chain 3, $\\phi^{(0)} = 30$'),
          xlab=TeX("$\\mu^{(m)}$"), ylab=TeX("$\\phi^{(m)}$"), xlim=c(-5,5), ylim=c(0,60) )
  lines(zz[1:m,2], zz[1:m,1], type='l', col='red')
}
```


```{r, fig.show='asis', fig.width=12, interval=1, fig.height=12, cache=T, fig.align='center'}

par(mfrow=c(3,3), mar=c(5,6,4,1)+.1)

cex=3

## plot chain 1 from iteration 1 up through iteration m
contour(mu, phi, density_posterior, nlevels = 30, 
        main = TeX('Chain 1, $\\phi^{(0)} = 40$'),
        xlab=TeX("$\\mu^{(m)}$"), ylab=TeX("$\\phi^{(m)}$"), 
        xlim=c(-5,5), ylim=c(0,60), 
        cex.lab=cex, cex.main=cex)
lines(xx[,2], xx[,1], type='l', col='blue')

## plot chain 2 from iteration 1 up through iteration m
contour(mu, phi, density_posterior, nlevels = 30, 
        main = TeX('Chain 2, $\\phi^{(0)} = 50$'),
        xlab=TeX("$\\mu^{(m)}$"), ylab=TeX("$\\phi^{(m)}$"),
        xlim=c(-5,5), ylim=c(0,60), 
        cex.lab=cex, cex.main=cex )
lines(yy[,2], yy[,1], col='orange', type='l')

## plot chain 3 from iteration 1 up through iteration m
contour(mu, phi, density_posterior, nlevels = 30, 
        main = TeX('Chain 3, $\\phi^{(0)} = 30$'),
        xlab=TeX("$\\mu^{(m)}$"), ylab=TeX("$\\phi^{(m)}$"),
        xlim=c(-5,5), ylim=c(0,60), 
        cex.lab=cex, cex.main=cex )
lines(zz[,2], zz[,1], type='l', col='red')

plot(xx[,2], type='l', col='blue', ylab=TeX("$\\mu^{(m)}$"), xlab="Iteration, m", 
        cex.lab=cex, cex.main=cex)
plot(yy[,2], type='l', col='orange', ylab=TeX("$\\mu^{(m)}$"), xlab="Iteration, m", 
        cex.lab=cex, cex.main=cex)
plot(zz[,2], type='l', col='red', ylab=TeX("$\\mu^{(m)}$"), xlab="Iteration, m", 
        cex.lab=cex, cex.main=cex)

plot(xx[,1], type='l', col='blue', ylab=TeX("$\\phi^{(m)}$"), xlab="Iteration, m", 
        cex.lab=cex, cex.main=cex)
plot(yy[,1], type='l', col='orange', ylab=TeX("$\\phi^{(m)}$"), xlab="Iteration, m", 
        cex.lab=cex, cex.main=cex)
plot(zz[,1], type='l', col='red', ylab=TeX("$\\phi^{(m)}$"), xlab="Iteration, m", 
        cex.lab=cex, cex.main=cex)

```
